Issue#1391Allow the wash form to be editable for a period of 24 hours
OpenSRP/opensrp-client-chw pull request #1495
Opened 2020-11-05 20:24 UTC by zzainulabidin

https://github.com/OpenSRP/opensrp-client-chw/issues/1391

2020-11-12 08:42 UTC, rkodev submitted a review, later dismissed

2020-11-18 06:49 UTC, rkodev requested changes

2020-11-18 06:49 UTC, rkodev commented on opensrp-chw/src/main/java/org/smartregister/chw/dao/WashCheckDao.java
> +        String sql = "select created_at from visits where visit_type = 'WASH check' and " +
IF using the `created_at` date, you should take the minimum between the `created_at` and `visit_date`. Data synced from the server are assigned  `new Date()` as the default date

2020-11-18 06:49 UTC, rkodev commented on opensrp-chw/src/main/java/org/smartregister/chw/dao/WashCheckDao.java
> +    public static void updateWashCheckVisitDetails(Long washDate, String baseEntityID,
You can client process events without persisting them in the database. The Event will be updated in the visit table.
Check example of client processing without saving
`org.smartregister.chw.core.utils.NativeFormProcessor#clientProcessForm`

2020-11-19 08:40 UTC, rkodev submitted a review, later dismissed

2020-11-20 06:36 UTC, qaziabubakar-vd approved these changes

2020-11-20 07:24 UTC, merged