CRVS bug fixes
opensrp/opensrp-client-chw pull request #2067
Opened 2022-06-08 05:48 UTC by qaziabubakar-vd

2022-06-10 11:03 UTC, allan-on requested changes
See review comments

2022-06-17 08:46 UTC, allan-on commented on opensrp-chw/src/crvs/assets/json.form/birth_certification_changed.json
> -        "openmrs_entity_id": "162052AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
Why was the entity_id removed?

2022-06-17 08:50 UTC, allan-on commented on opensrp-chw/src/crvs/assets/json.form/birth_certification_changed.json
>          "openmrs_entity": "concept",
Why was the entity_id removed?

2022-06-17 08:55 UTC, allan-on commented on opensrp-chw/src/crvs/assets/json.form/birth_certification_changed.json
> -        "openmrs_entity_id": "162052AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
Why ws this entity_id removed?

2022-06-23 12:25 UTC, qaziabubakar-vd commented on opensrp-chw/src/crvs/assets/json.form/out_of_area_death_form.json
> +          "err": "Number must take the format of ##/####"
Relevance is added

2022-06-23 12:25 UTC, qaziabubakar-vd commented on opensrp-chw/src/crvs/assets/json.form/birth_certification_changed.json
> -        "openmrs_entity_id": "162052AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
Relevance is added

2022-06-23 15:07 UTC, merged